# Generated by Django 3.0.5 on 2020-10-07 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_number', models.IntegerField(default=0)),
                ('type_name', models.CharField(max_length=50)),
                ('type_description', models.CharField(default=None, max_length=1024)),
                ('type_description_mini', models.CharField(default=None, max_length=1024)),
                ('type_img', models.ImageField(upload_to='imgs/helpers/')),
                ('type_img_mini', models.ImageField(default='/img/helpers/broker-01.png', upload_to='imgs/helpers/')),
                ('allow_post', models.BooleanField(default=False)),
                ('allow_buy', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'account_type',
            },
        ),
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=500)),
                ('phone', models.CharField(default=None, max_length=500)),
                ('user_city', models.CharField(default=None, max_length=15)),
                ('user_zip', models.CharField(default=None, max_length=15)),
                ('company_name', models.CharField(default=None, max_length=500)),
                ('company_hours_of_operation', models.CharField(default=None, max_length=500)),
                ('company_Latitude', models.FloatField(default=None, max_length=50)),
                ('company_Longitude', models.FloatField(default=None, max_length=50)),
                ('company_url', models.CharField(default=None, max_length=500)),
                ('company_description', models.CharField(default=None, max_length=500)),
                ('accountType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.account_type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
