# Generated by Django 3.0.5 on 2020-10-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_country',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
